
-------------------EJEMPLO PROCEDURE-----------------------------------------------------------
CREATE PROCEDURE CALCULO_AVERIAS @MES int, @AÑO int AS
EXEC CALCULO_AVERIAS MES = 09 AND AÑO = 2019;
----------------------------------------------------------------------------------------

------------------------MERGE--------------------------------

CREATE TABLE TEST2 (ID INT, EDA INT, NADA INT)
INSERT INTO TEST2 VALUES (2, 700, 80)
SELECT * FROM TEST1;
SELECT * FROM TEST2;

MERGE TEST1 A USING TEST2 B
ON (A.ID = B.ID)
WHEN MATCHED
	AND A.EDA < 1000
	AND B.EDA <1000
	THEN UPDATE SET
		A.EDA = B.EDA ,
		A.NADA = B.NADA;

---------------------------SMA_ADSL_2019.SQL------------------------------
UPDATE (SELECT * FROM TEST1 A JOIN TEST2 B ON A.ID = B.ID)
SET A.EDA = B.EDA
WHERE A.ID = B.ID

MERGE SMA_ADSL A USING CODLIQ_ADSL_2017 B
ON (A.CODLIQ = B.CODLIQ)	
WHEN MATCHED
	AND A.COD_LIQ = B.COD_LIQ
	AND A.MM_LIQ = 09
	AND AA_LIQ = 2019
    THEN UPDATE SET 
        A.TELEFONO = B.CLASIF,
        A.MM_LIQ = B.AA_LIQ

UPDATE SMA_ADSL
SET CSEG = "E"
WHERE CODSEG IN ("00","01","02","03","04","05","06","07")
AND MM_LIQ = 09

MERGE SMA_ADSL A USING CODLIQ_ADSL_2017 B
ON (A.CAMPO1 = B.CAMPO2)	
WHEN MATCHED
	AND A.COD_LIQ = B.COD_LIQ
	AND A.MM_LIQ = 09
	AND AA_LIQ = 2019
    THEN UPDATE SET 
        A.TELEFONO = B.CLASIF;

MERGE SMA_ADSL A USING RUTEMPP B
ON (A.MDF = B.MDF)	
WHEN MATCHED
	AND LEN(TRIM(A.AMDF)) = 4
	AND TRIM(A.CSEG) = "E"
	AND A.MM_LIQ = 09
    THEN UPDATE SET
        A.MODRUT = 1

MERGE SMA_ADSL A USING MDF_INSOURCING2015 B
ON (A.MDF = B.MDF)	
WHEN MATCHED
	AND TRIM(A.CODLIQ) IN ("31","32","33","34")
	AND B.SWITCH = ".T." 
	AND MM_LIQ = 09
	AND AA_LIQ = 2019
    THEN UPDATE SET
        A.INSMDF = 1;

MERGE SMA_ADSL A USING MODARM B
ON (A.MDF = B.MDF)	
WHEN MATCHED
	AND TRIM(A.CODLIQ) IN ("15","24") 
	AND MM_LIQ = 09 
	AND AA_LIQ = 2019
    THEN UPDATE SET
        A.MODARM = 1

-- CODIGO GLORIA
SELECT * FROM "d:\calc_averias\ACUM\2019\SMA_ADSL" GROUP BY AVERIA INTO TABLE "d:\calc_averias\ACUM\2019\SMA_ADSL2"

-- HALLAR REPETIDOS
CREATE VIEW SMA_ADSL2 AS (
SELECT NOMBRE, COUNT(CLIENTE) FROM TABLA GROUP BY PAIS HAVING COUNT CLIENTE > 1)

CREATE VIEW SMA_ADSL2 AS (
SELECT * FROM SMA_ADSL2 WHERE ALLTRIM(ESTALIQ) in ("ZEI","STAR","RTNC","PEX","PAGE","VOIP") AND MODRUT=0  
AND MODARM=0 AND INSMDF=0 AND telefono="EFECTIVA" and MM_LIQ = 09)
---------------------------------------------------------------------------------------------------------------------





	




