------------------------MERGE--------------------------------
-------------------SMA_ADSL_2019.SQL-----------------

-- APPEND FROM STB0719 = SUBIR ARCHIVO STB0719 A LA TABLA SMA_STB

-- LUEGO DE AÑADIR ESTAS FILAS A LA TABLA SMA_STB, SE ACTUALIZA

--DROP TABLE SMA_STB
--SELECT * INTO SMA_STB FROM STB
ALTER TABLE SMA_STB ADD CSEG VARCHAR(255)

UPDATE SMA_STB
SET CSEG = 0
WHERE CSEG IS NULL

UPDATE SMA_STB
SET CSEG = 'E'
WHERE CODSEG IN ('00','01','02','03','04','05','06','07','0','1','2','3','4','5','6','7')
AND MM_LIQ = 7


ALTER TABLE SMA_STB ADD MODRUTAS INT

UPDATE SMA_STB
SET MODRUTAS = 0
WHERE MODRUTAS IS NULL

UPDATE SMA_STB
SET MODRUTAS = 1
WHERE DBO.TRIM(ZONAL) = 'LIMA' AND CSEG = 'E' AND MM_LIQ = 7
----------------------------------------------------------------------------------------

UPDATE A
SET A.MODRUTAS = 1
FROM SMA_STB A JOIN RUTEMPP B ON A.MDF = B.MDF
WHERE LEN(DBO.TRIM(TI_LIQN)) = 4
	AND CSEG = 'E'
	AND A.MM_LIQ = 7
---------------------------------------------------------------------------------
ALTER TABLE SMA_STB ADD INS_MDF INT

UPDATE SMA_STB
SET INS_MDF = 0
WHERE INS_MDF IS NULL

UPDATE A
SET INS_MDF = 1
FROM SMA_STB A JOIN MDF_INSOURCING2015 B ON A.MDF = B.MDF
WHERE DBO.TRIM(TI_LIQN) IN ('31','32','33','34')
      --AND SWITCH = '.T.'
      AND A.MM_LIQ = 7

--------------------------------------------------------------------------------------------------------------------
-- FALTA IMPORTAR LA TABLA CODLIQ_STB_2017
ALTER TABLE SMA_STB ADD CLASIF NVARCHAR(255)

SELECT * FROM CODLIQ_STB_2017

UPDATE A
SET A.CLASIF = B.CLASIF
FROM SMA_STB A JOIN CODLIQ_STB_2017 B ON A.TI_LIQN = B.TI_LIQN
WHERE A.MM_LIQ = 7

--------------------------------------------------------------------------------
ALTER TABLE SMA_STB ADD MODARM INT

UPDATE SMA_STB
SET MODARM = 0
WHERE MODARM IS NULL

UPDATE A
SET MODARM = 1
FROM SMA_STB A JOIN MODARM B ON A.MDF = B.MDF
WHERE  DBO.TRIM(A.TI_LIQN) IN ('15', '24')
	  AND A.MM_LIQ = 7

-- CODIGO GLORIA GROUP BY -- > VISUAL FOX PRO
SELECT * FROM SMA_STB GROUP BY COD_UNICO INTO TABLE 'd:\calc_averias\ACUM\2019\SMA_STB4'

SELECT * INTO SMA_STB_VW FROM SMA_STB


CREATE OR ALTER VIEW STB_07 AS (
SELECT * FROM SMA_STB_VW
WHERE MODRUTAS=0 AND INS_MDF=0 AND MODARM=0  --AND DBO.TRIM(CLASIF)='EFECTIVA'
AND SUBSTRING(COD_UNICO,1,2)<>'RU' AND MM_LIQ=7
);